<../../mkconfig

TARG=\
	regmonitor.dis\

SYSMODULES=\
	sys.m\
	registries.m\

MODULES=\
	../../../logger/module/logger.m\
	../../../hashtable/module/hashtable.m\
	../../module/regmonitor.m\

DISBIN=../../dis/lib

<$ROOT/mkfiles/mkdis

